
import Header from '../components/products/Header.jsx';
import ResultHeader from '../components/products/ResultHeader.jsx';
import ProductsGrid from '../components/products/ProductsGrid.jsx';

function Products() {
  const data = {
  "products": [
    {
      "id": 34999,
      "product_display_name": "Fabindia Women Black & Mustard Stole",
      "article_type": "Stoles",
      "base_colour": "Black",
      "fabric": "Cotton",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Fabindia",
      "price": 290.0,
      "discounted_price": 290.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/44135729acc70ea13036d227e97ffb57_images.jpg",
      "similarity_score": 0.5,
      "style_note": "This Fabindia cotton stole offers a classic wrap accessory in a black and mustard yellow print with neatly stitched edges.",
      "ai_note_available": true
    },
    {
      "id": 34570,
      "product_display_name": "Tonga Women Printed Black Dress",
      "article_type": "Dresses",
      "base_colour": "Black",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Tonga",
      "price": 1650.0,
      "discounted_price": 1650.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/38e2a2b27ef024b31caccec4cd45a6d2_images.jpg",
      "similarity_score": 0.5,
      "style_note": "This printed black dress captures elements of your search with its shawl neckline and a design described as a fusion of vintage style and contemporary details.",
      "ai_note_available": true
    },
    {
      "id": 47640,
      "product_display_name": "Carlton London Women Brown Shoes",
      "article_type": "Casual Shoes",
      "base_colour": "Brown",
      "fabric": null,
      "fit": null,
      "season": "Winter",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Carlton London",
      "price": 1695.0,
      "discounted_price": 1695.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/7be41c1af7c72e28b5c561e4a00aa94c_images.jpg",
      "similarity_score": 0.33333334,
      "style_note": "These slip-on flats showcase the cheetah print you are looking for, featuring an all-over cheetah pattern across a brown hairy upper.",
      "ai_note_available": true
    },
    {
      "id": 39219,
      "product_display_name": "Femella Women Black Animal Printed Kaftan Top",
      "article_type": "Tops",
      "base_colour": "Black",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 590.0,
      "discounted_price": 590.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/d16b5c1f00a5c9ffff80ffcbba48aabd_images.jpg",
      "similarity_score": 0.33333334,
      "style_note": "Featuring an animal print on a blended black fabric, this kaftan top offers a flowy silhouette with flutter sleeves.",
      "ai_note_available": true
    },
    {
      "id": 47641,
      "product_display_name": "Carlton London Women Cream Shoes",
      "article_type": "Casual Shoes",
      "base_colour": "Cream",
      "fabric": null,
      "fit": null,
      "season": "Winter",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Carlton London",
      "price": 1795.0,
      "discounted_price": 1795.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/8d1865d347e1a2ef412f86c64afda164_images.jpg",
      "similarity_score": 0.25,
      "style_note": "These cream slip-on shoes feature a distinct cheetah print on faux animal hair across the toe box.",
      "ai_note_available": true
    },
    {
      "id": 59904,
      "product_display_name": "Femella Women Pink Scarf",
      "article_type": "Scarves",
      "base_colour": "Pink",
      "fabric": null,
      "fit": null,
      "season": "Fall",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 390.0,
      "discounted_price": 390.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Femella-Women-Pink-Scarf_8ae25bb07a168cb42d54ec40d475e5ed_images.jpg",
      "similarity_score": 0.25,
      "style_note": "If you are looking for lightweight neckwear, this pink woven scarf features an all-over print and tasseled edges.",
      "ai_note_available": true
    },
    {
      "id": 47663,
      "product_display_name": "Femella Women Brown Leopard Print Scarf",
      "article_type": "Scarves",
      "base_colour": "Brown",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 250.0,
      "discounted_price": 250.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/c5a1a40df456e3a79334a595dbd04bf6_images.jpg",
      "similarity_score": 0.2,
      "style_note": "This brown Femella scarf provides an animal print accessory option featuring a classic leopard pattern.",
      "ai_note_available": true
    },
    {
      "id": 33165,
      "product_display_name": "Sepia Women Blue Top",
      "article_type": "Tops",
      "base_colour": "Blue",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Sepia",
      "price": 599.0,
      "discounted_price": 599.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/bfd4d94d3c600260e1a8a3e26ce455a1_images.jpg",
      "similarity_score": 0.2,
      "style_note": "This pale blue top includes a shawl neck detail and is styled for a vintage feel.",
      "ai_note_available": true
    },
    {
      "id": 58512,
      "product_display_name": "Tonga Women Printed Black Top",
      "article_type": "Tops",
      "base_colour": "Cream",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Tonga",
      "price": 1290.0,
      "discounted_price": 1290.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Tonga-Women-Printed-Black-Top_3ad8bcdc34bae888bc63b5d8f1071904_images.jpg",
      "similarity_score": 0.16666667,
      "style_note": "This tops was retrieved based on its cream color, blended material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 39140,
      "product_display_name": "Aneri Women Black & Maroon Salwar Suit",
      "article_type": "Kurta Sets",
      "base_colour": "Black",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Ethnic",
      "gender": "Women",
      "brand_name": "Aneri",
      "price": 3749.0,
      "discounted_price": 3749.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/4d16721ce6d31a02786fa271a40dbc86_images.jpg",
      "similarity_score": 0.16666667,
      "style_note": "This kurta sets was retrieved based on its black color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 45425,
      "product_display_name": "Rocia Women Black Sandals",
      "article_type": "Flats",
      "base_colour": "Black",
      "fabric": null,
      "fit": null,
      "season": "Winter",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Rocia",
      "price": 590.0,
      "discounted_price": 590.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/1f10c3d52e57803841cd6a328b0b86df_images.jpg",
      "similarity_score": 0.14285715,
      "style_note": "This flats was retrieved based on its black color, suitability for winter for your search.",
      "ai_note_available": false
    },
    {
      "id": 57897,
      "product_display_name": "Femella Women Black & Grey Scarf",
      "article_type": "Scarves",
      "base_colour": "White",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 250.0,
      "discounted_price": 250.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Femella-Women-Black---Grey-Scarf_5a8f23cda118109fb2fc57632ca39886_images.jpg",
      "similarity_score": 0.14285715,
      "style_note": "This scarves was retrieved based on its white color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 45426,
      "product_display_name": "Rocia Women Brown Sandals",
      "article_type": "Flats",
      "base_colour": "Brown",
      "fabric": null,
      "fit": null,
      "season": "Winter",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Rocia",
      "price": 590.0,
      "discounted_price": 590.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/161866c694d7c056dcb9481f4185f2cb_images.jpg",
      "similarity_score": 0.125,
      "style_note": "This flats was retrieved based on its brown color, suitability for winter for your search.",
      "ai_note_available": false
    },
    {
      "id": 23210,
      "product_display_name": "Aneri Women Sequin Brown Top",
      "article_type": "Tops",
      "base_colour": "Brown",
      "fabric": null,
      "fit": null,
      "season": "Fall",
      "usage": "Ethnic",
      "gender": "Women",
      "brand_name": "Aneri",
      "price": 1495.0,
      "discounted_price": 1495.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/1cd7308206ce6fc2c89102182f5205ac_images.jpg",
      "similarity_score": 0.125,
      "style_note": "This tops was retrieved based on its brown color, suitability for fall for your search.",
      "ai_note_available": false
    },
    {
      "id": 58505,
      "product_display_name": "Tonga Women Printed Brown Dress",
      "article_type": "Dresses",
      "base_colour": "Off White",
      "fabric": "Polyester",
      "fit": null,
      "season": "Fall",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Tonga",
      "price": 2250.0,
      "discounted_price": 2250.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Tonga-Women-Printed-Brown-Dress_9ca7c682d9c9a27a1e83b9078489047e_images.jpg",
      "similarity_score": 0.11111111,
      "style_note": "This dresses was retrieved based on its off white color, polyester material, suitability for fall for your search.",
      "ai_note_available": false
    },
    {
      "id": 56887,
      "product_display_name": "HM Women Black Heels",
      "article_type": "Heels",
      "base_colour": "Blue",
      "fabric": null,
      "fit": null,
      "season": "Winter",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "HM",
      "price": 1399.0,
      "discounted_price": 1399.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/HM-Women-Blue-Sandals_cffa5f249625008cb50ef4ef48708787_images.jpg",
      "similarity_score": 0.11111111,
      "style_note": "This heels was retrieved based on its blue color, suitability for winter for your search.",
      "ai_note_available": false
    },
    {
      "id": 34978,
      "product_display_name": "Fabindia Women Black Stole",
      "article_type": "Stoles",
      "base_colour": "Black",
      "fabric": "Silk",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Fabindia",
      "price": 1190.0,
      "discounted_price": 1190.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/7438d4ff454d304ff9ff9a8baf528c28_images.jpg",
      "similarity_score": 0.1,
      "style_note": "This stoles was retrieved based on its black color, silk material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 31292,
      "product_display_name": "Puma Women Script Black Top",
      "article_type": "Tops",
      "base_colour": "Black",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Puma",
      "price": 1099.0,
      "discounted_price": 769.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/ef7624f1ac58db7fd6e03259d0f7f179_images.jpg",
      "similarity_score": 0.1,
      "style_note": "This tops was retrieved based on its black color, blended material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 25951,
      "product_display_name": "Femella Women Printed Black & Cream Scarf",
      "article_type": "Scarves",
      "base_colour": "Black",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 290.0,
      "discounted_price": 290.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/c5594b4fa6aa61f7288f31d43e8f7e09_images.jpg",
      "similarity_score": 0.09090909,
      "style_note": "This scarves was retrieved based on its black color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 42920,
      "product_display_name": "French Connection Women Grey Wallet",
      "article_type": "Wallets",
      "base_colour": "Grey",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "French Connection",
      "price": 1999.0,
      "discounted_price": 1999.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/0305a2f2216a39afffeb7fd6820b2815_images.jpg",
      "similarity_score": 0.09090909,
      "style_note": "This wallets was retrieved based on its grey color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 42862,
      "product_display_name": "French Connection Women Grey Clutch",
      "article_type": "Clutches",
      "base_colour": "Grey",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "French Connection",
      "price": 3699.0,
      "discounted_price": 3699.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/ecd3b955e4acf8e119993e3cb0f912d0_images.jpg",
      "similarity_score": 0.083333336,
      "style_note": "This clutches was retrieved based on its grey color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 34967,
      "product_display_name": "Fabindia Women Off White Printed Stole",
      "article_type": "Stoles",
      "base_colour": "Off White",
      "fabric": "Cotton",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Fabindia",
      "price": 630.0,
      "discounted_price": 630.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/b0b2c6973cfe240442465c2e22f3ca00_images.jpg",
      "similarity_score": 0.083333336,
      "style_note": "This stoles was retrieved based on its off white color, cotton material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 54992,
      "product_display_name": "Femella Women Black & Beige Shrug",
      "article_type": "Shrug",
      "base_colour": "Beige",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 550.0,
      "discounted_price": 550.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Femella-Women-Black---Beige-Shrug_3baff3492cf39bbdfbcd61aca1b353e6_images.jpg",
      "similarity_score": 0.07692308,
      "style_note": "This shrug was retrieved based on its beige color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 31293,
      "product_display_name": "Puma Women Script Green Top",
      "article_type": "Tops",
      "base_colour": "Green",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Puma",
      "price": 1099.0,
      "discounted_price": 1099.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/438fa8599e452ede8a2f18a750e07190_images.jpg",
      "similarity_score": 0.07692308,
      "style_note": "This tops was retrieved based on its green color, blended material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 59907,
      "product_display_name": "Femella Women Off White Printed Scarf",
      "article_type": "Scarves",
      "base_colour": "Off White",
      "fabric": null,
      "fit": null,
      "season": "Fall",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 450.0,
      "discounted_price": 450.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Femella-Women-White-Scarf_9696428a56e68b7e9b5eda82ee237df0_images.jpg",
      "similarity_score": 0.071428575,
      "style_note": "This scarves was retrieved based on its off white color, suitability for fall for your search.",
      "ai_note_available": false
    },
    {
      "id": 42872,
      "product_display_name": "French Connection Women Grey Clutch",
      "article_type": "Clutches",
      "base_colour": "Grey",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "French Connection",
      "price": 2999.0,
      "discounted_price": 2999.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/cca42ec5b22286eac8507b7cb736fe4b_images.jpg",
      "similarity_score": 0.071428575,
      "style_note": "This clutches was retrieved based on its grey color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 47670,
      "product_display_name": "Femella Women Cream and Black Printed Scarf",
      "article_type": "Scarves",
      "base_colour": "Cream",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Femella",
      "price": 250.0,
      "discounted_price": 250.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/07e50b2f8f8aef78705b4f03f663d97c_images.jpg",
      "similarity_score": 0.06666667,
      "style_note": "This scarves was retrieved based on its cream color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 39168,
      "product_display_name": "Aneri Women Grey Printed Kurta",
      "article_type": "Kurtas",
      "base_colour": "Grey",
      "fabric": null,
      "fit": null,
      "season": "Summer",
      "usage": "Ethnic",
      "gender": "Women",
      "brand_name": "Aneri",
      "price": 1999.0,
      "discounted_price": 1999.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/79734bb30a2ee077e17ebb7a3b9f4579_images.jpg",
      "similarity_score": 0.06666667,
      "style_note": "This kurtas was retrieved based on its grey color, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 6891,
      "product_display_name": "Forever New Women Long Black Jacket",
      "article_type": "Jackets",
      "base_colour": "Black",
      "fabric": "Blended",
      "fit": null,
      "season": "Summer",
      "usage": "Casual",
      "gender": "Women",
      "brand_name": "Forever New",
      "price": 6000.0,
      "discounted_price": 6000.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/7bb3c8ed3c606b05b131e72efc89b0e1_images.jpg",
      "similarity_score": 0.0625,
      "style_note": "This jackets was retrieved based on its black color, blended material, suitability for summer for your search.",
      "ai_note_available": false
    },
    {
      "id": 49918,
      "product_display_name": "Fabindia Brown Printed Ajrakh Dhonekhali Saree",
      "article_type": "Sarees",
      "base_colour": "Brown",
      "fabric": null,
      "fit": null,
      "season": "Fall",
      "usage": "Ethnic",
      "gender": "Women",
      "brand_name": "Fabindia",
      "price": 2990.0,
      "discounted_price": 2990.0,
      "image_url": "http://assets.myntassets.com/v1/images/style/properties/Fabindia-Women-Mustard-Sari_dd9a6905988bb97bd47db8e12e556ab4_images.jpg",
      "similarity_score": 0.0625,
      "style_note": "This sarees was retrieved based on its brown color, suitability for fall for your search.",
      "ai_note_available": false
    }
  ],
  "query": "vintage cheetah print shawl",
  "total": 30,
  "ai_generated": true,
  "search_mode": "text",
  "error_message": null
}
  return (
    <>
        <Header />
        <ResultHeader total={data.total} userQuery={data.query} />  
        <ProductsGrid data={data}  />
    </>
  );
}

export default Products;